### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/organization-genomics#108]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. It looks like this lesson is pretty clean and complete, so it may be that there isn't much need for community contributions. Please let me know if you have any questions!

**Comment by hoytpr** [comment]
Not going to go into minutia but a little wordsmithing is needed throughout e.g. “In order to be able to”. 
For the purpose of lesson release my assessment so far:

     * [ ]  Example code chunks run as expected
(Will have to check the .git/config code for fixing CR/LF tomorrow, but should note it’s not identical to the code in the linked examples. Also note that copy-paste resulted in **doubly** indented code for lines 2 & 3 which may or may not affect anything. Also note the lesson says Windows machines have export problems resulting in "data1, data2\r, 1, 2\r" which I have tested extensively and cannot reproduce in Windows, but the links point to problems with Macs exporting Excel files)
( Related to .csv files: C. Titus Brown recommended we include a link to: (https://donatstudios.com/Falsehoods-Programmers-Believe-About-CSVs))
 
     * [X]  Challenges / exercises run as expected
 
     * [ ]  Challenge / exercise solutions are correct

(00-intro/index.html has an exercise with no solution. Call this discussion or thought project? )
(I'll probably get some pushback on this but... considering our policies on inclusivity, is the "Example: You find one male, and one female of the same species. You enter this as 1M, 1F" perhaps too binary for our audience or am I being way too PC?)

     * [X]  Call out boxes (exercises, discussions, tips, etc) render correctly
 
     * [X]  A schedule appears on the lesson homepage (e.g. not “00:00”)

     * [x]  Each episode includes learning objectives
 (Discussion page has no questions objectives times, or keypoints.)

     * [x]  Each episode includes questions

     * [x]  Each episode includes key points

     * [X]  Setup instructions are up-to-date, correct, clear, and complete

     * [X]  File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
 
     * [X]  Some Instructor notes are provided
(But, formatting on Instructor notes is not exactly consistent. Needs bullets and Headers with same colors

     * [X]  Lesson links work as expected
(But, in 02, most links go directly to a source, rather than another lesson so OpenRefine should link to http://openrefine.org/download.html or be reworded.)
(Also, the link to White, et al. 2013, goes to the [preprint](https://peerj.com/preprints/7/), not the final manuscript at [Ecology and Evolution](https://ojs.library.queensu.ca/index.php/IEE/article/view/4608) which is okay if the final version is pay-walled.)

**Comment by ErinBecker** [comment]
Thanks for your extensive work on this @hoytpr. A few responses to specific points:

- For the exercise without a solution, you can change it to a Discussion box using the `{: .discussion}` tag. Thanks for catching this.
- For the "1 male, 1 female" example, since we're dealing with non-human species, male and female designations based on physical observation is accurate. (As far as we know) lizards, mice, etc, don't have socially encoded gender roles!

**Comment by hoytpr** [comment]
Previous "Discussion" on page worked well with hidden "Solution", so left the format as is but changed the header to "Discusssion". 
(I've seen more than a few non-binary chimeric mice, but thanks for the "socially encoded" advice.)

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by hoytpr** [comment]
Yes. Will finish the code chunks analysis today. The Arizona Bug BBQ was fantastic. @fmichonneau did a great job getting through knitr. Can't wait until we have a Genomics Workshop at OKState!  Wish we could have another BBQ here. The middle of the country needs this so much!

**Comment by ErinBecker** [comment]
@hoytpr - could you please confirm whether this lesson is ready for release? @fmichonneau and I are working on the releases this week.

**Comment by hoytpr** [comment]
Hi @ErinBecker  
**Set me up with an AWS and I'll go through it today completely.**

**Comment by hoytpr** [comment]
I have now verified the Cyverse connections for shell work, and that R-studio works (already checked the commands using a local R-studio). This lesson is ready. I noticed ONE thing that you have to click on the link to the instance an extra time (image Click-on-this-link.png) in order to get to the page where you click on "open Old Web Shell" rather than "Open web shell" button on your image dashboard." (image then click onopen-old-shell.png) as described in the lesson on Cyverse (in my case https://atmo.cyverse.org/application/images/1699).  
**The images below probably don't work, I'll fix them**
![Click-on-this-link1](https://user-images.githubusercontent.com/5910884/59231413-344ffc80-8ba6-11e9-8096-75ba38555690.png)
![then-click-onopen-old-shell](https://user-images.githubusercontent.com/5910884/59231420-3914b080-8ba6-11e9-9ca9-7c964a2ba66b.png)

**Comment by ErinBecker** [comment]
@hoytpr - I think your most recent message went to my email and not to this thread. From you email it looks like this lesson is complete and ready to go! So I'll check off those remaining items and we'll go ahead and include this lesson in the publication. Thanks @hoytpr!

**Comment by ErinBecker** [comment]
Awesome work @datacarpentry/organization-genomics-maintainers and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
Lesson released! :tada: https://doi.org/10.5281/zenodo.3260317
