### ISSUE TITLE
Ep1 Data Tidyness Metadata Example

### ISSUE THREAD

**Issue by FrancesWong** [datacarpentry/organization-genomics#123]
Hi! 

The screenshot example data under "Structuring data in spreadsheets" is a great example of the good habits described above it however I think it could be misleading for the first two rows to be global headers (versus column names). It could interfere with reading the table directly into R. I know there are parameters to skip some rows but this may be easier to beginners. Another guideline that could be added is the first column are unique sample identifiers and the first row to be unique column names describing ... the descriptions!

I would also suggest to move the definition of metadata to a more obvious area since it could be easily missed under the discussion box and is the dominate concept of the page. 

Looking forward to using the genomics lesson! 

Cheers, 
-Frances

**Comment by hoytpr** [comment]
Hi @FrancesWong and apologies for the late response. First, thanks for the idea about moving the definition of metadata to make it more obvious. We should do this and you are welcome to submit a PR on this if you want. As far as changing the Table screenshot, I am sympathetic that it could be harder for beginners (not long ago, I was very much a beginner). But because this is a discussion question, the global headers are something that might come up in datafiles (I know I've seen some). Instructors should point out that global headers (or even column names sometimes) are not always used, and certainly not good for importing into R.
