### ISSUE TITLE
SraRunTable.txt downloads as CSV, not TSV

### ISSUE THREAD

**Issue by esallychang** [datacarpentry/organization-genomics#127]
In the updated version of the SRA Run Selector Page, the downloaded SraRunTable.txt is actually now a comma-delimited file rather than a tab-delimited file as stated on the current version of the "Examining Data on the NCBI SRA Database" page.

 Students will need to specify that their spreadsheet program interpret it as comma-delimited, so I suggest the following language: "Using your choice of spreadsheet program, open the SraRunTable.txt file. You may need to tell the program that this is a comma-delimited file in order to have the data separated properly into columns."

**Comment by hoytpr** [comment]
Hello @esallychang and thanks very much for this contribution! This occurs because of the newer NCBI website being in the cloud, and you are correct! NCBI has **also** changed the the Run Table button to a button that reads "Metadata". It may be that we have to say *"Depending on whether you are using the new or older version of the Run Website, you may need to tell the spreadsheet program that this is a tab-delimited (old version) or comma delimited (new version)."* Thanks again  and I'll get back to this in the afternoon.

**Comment by ewallace** [comment]
Boosting this issue, we had the same point teaching this morning, and I like @hoytpr 's proposed fix.
