### ISSUE TITLE
Ask about learners' science in data tidiness first discussion?

### ISSUE THREAD

**Issue by ewallace** [datacarpentry/organization-genomics#132]
For our online teaching today, during [data tidiness](https://datacarpentry.org/organization-genomics/01-tidiness/index.html) we did Discussion 1 "What kinds of data and information have you generated before you sent your DNA/RNA off for sequencing?" in the collaborative document and added some questions.

We tried:
* What's your name? 
* What kind of sequencing data are you collecting? 
* What question is your experiment answering? 
* What kinds of data and information have you generated before you sent your DNA/RNA off for sequencing?

We gave an example:
* **Edward:** CLIP-seq/CRAC. Asking which RNA is bound by my yeast protein (Pab1) and how that changes as cells grow. Have data on cell growth (timepoints and optical density) in text format...

Good points:
* instructors got to see the range of projects being worked on (metagenomics, RNA-seq, DNA-seq, etc).
* we had a good discussion about linked metadata, e.g. a plant scientist also takes photos of their plants, an ecologist has site sampling data.
* learners got to share lessons they'd learned.
* for some learners, it may have been the first time they'd thought about it.
* it only added 5 minutes.

Bad points
* only about 1/2 of learners got to the point of talking about file types of that data.

Is it useful to expand this discussion in the lesson?

**Comment by hoytpr** [comment]
Hi @ewallace   and thanks for your comments. In my opinion these are great new questions but they assume the learners have data, which might not be true. Because this is a discussion, you should feel free to "Read the room" and ask questions like this.  But we probably don't need to change the lesson.  Maybe you could do a pre-workshop survey to ask these questions, and present the range of answers. Many instructors make adjustments to this section, and they **should**, depending on the audience. Does this make sense to you? 
Peter

**Comment by ewallace** [comment]
Hi @hoytpr, thanks for this feedback, makes perfect sense.

So should we adapt this into the instructor notes?

**Comment by hoytpr** [comment]
@ewallace  Yes that would be great! Would you like to do a PR? If not I can do it.
