### ISSUE TITLE
Missing content in Introduction episode.

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/organization-genomics#31]
The [opening page for this repo](http://www.datacarpentry.org/organization-genomics/) has a lot of place holders for 

- intro text
- what they will learn
- why this is important
- key questions

Sorry if I missed an issue that covers this.

**Comment by mkuzak** [comment]
Hi @sstevens2 thank you for submitting this issue. There is no issue that covers it yet. I will rename this issue to "Missing content in Introduction episode" and add a checklist of things that need to be added.

**Comment by sstevens2** [comment]
Thanks @mkuzak!  Sorry I got started on Issue Bonanza early!  I figured I had time while I helped in this SWC workshop and didn't notice the time.

**Comment by mkuzak** [comment]
things to address in this issue:

- [x] introduction text
- [x] lesson objectives
- [x] why is are the things taught here important?
- [ ] key questions
- [x] pre requisites

**Comment by mkuzak** [comment]
@sstevens2 no worries, for me it's better, I'm in European time zone :)

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/organization-genomics/pull/43

Thanks @sstevens2 for putting in this PR. #43 covers most of the items listed in @mkuzak's checklist above, except for key questions. We generally don't include key questions in the lesson overview page, but in each of the individual episode pages.
